name: Linienroboter
title: Linienroboter
author: Maik Rehburg
remote_theme: wago-enterprise-education/wago-github-pages-theme
lang: de
plugins:
- jemoji
- jekyll-redirect-from
- jekyll-relative-links
