name: Linienroboter
title: Linienroboter
author: Louis Krumme
email: finnerik.hilgers@WAGO.com
remote_theme: wago-enterprise-education/wago-github-pages-theme
lang: de
plugins:
- jemoji
- jekyll-redirect-from
- jekyll-relative-links
